# Avoid useless messages
comment: off

coverage:
  status:
    project:
      default:
        # Commits pushed to master should not decrease
        # the overall project coverage by more than 1%
        target: auto
        threshold: 1%
    patch:
      default:
        # Be tolerant on slight code coverage diff on
        # PR to limit noisy coverage status on GitHub
        target: auto
        threshold: 1%
